### ISSUE TITLE
Bug: SQLite database file cannot be opened in svelocker-ui container

### ISSUE THREAD

**Issue by jk** [kmendell/svelocker-ui#41]
### Bug description

I'm trying to run this registry ui. But when I start the image I get the following error message:

```
svelocker-ui-1  | Node.js v22.14.0
svelocker-ui-1  | Initializing data directory...
svelocker-ui-1  |
svelocker-ui-1  | /app/node_modules/better-sqlite3/lib/database.js:69
svelocker-ui-1  |               [util.cppdb]: { value: new addon.Database(filename, filenameGiven, anonymous, readonly, fileMustExist, timeout, verbose || null, buffer || null) },
svelocker-ui-1  |                                      ^
svelocker-ui-1  | SqliteError: unable to open database file
svelocker-ui-1  |     at new Database (/app/node_modules/better-sqlite3/lib/database.js:69:26)
svelocker-ui-1  |     at file:///app/build/server/chunks/db-IF3MSq00.js:155:12
svelocker-ui-1  |     at ModuleJob.run (node:internal/modules/esm/module_job:271:25)
svelocker-ui-1  |     at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:578:26)
svelocker-ui-1  |     at async get_hooks (file:///app/build/server/index.js:520:49)
svelocker-ui-1  |     at async file:///app/build/server/index.js:4825:24
svelocker-ui-1  |     at async Server.init (file:///app/build/server/index.js:4823:5)
svelocker-ui-1  |     at async file:///app/build/handler.js:1208:1 {
svelocker-ui-1  |   code: 'SQLITE_CANTOPEN'
svelocker-ui-1  | }
```

here's the `docker-compose.yml` I'm using

```yaml
version: '3.9'

services:
  svelocker-ui:
    image: ghcr.io/kmendell/svelocker-ui:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./data:/app/data

  cache:
    image: registry:2.8.3
    restart: unless-stopped
    init: true
    ports:
     - 443:443
     - 5001:5001
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml:ro
      - ./server.chain.crt:/etc/ssl/server.crt:ro
      - ./server.key:/etc/ssl/server.key:ro
      - ./storage:/var/lib/registry:rw
```

and the `.env` file:

```ini
PUBLIC_REGISTRY_URL=https://dockerhub-cache.example.tld
PUBLIC_REGISTRY_NAME=My DockerHub Cache
DB_PATH=svelockerui.db
REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin='[https://dockerhub-cache.example.tld]'
REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods='[HEAD,GET,OPTIONS,DELETE]'
REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials='[true]'
REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers='[Authorization,Accept,Cache-Control]'
REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers='[Docker-Content-Digest]'
```

It also doesn't run if I don't use a bind mount for `/app/data` nor if I chmod the `./data` directory to `666`.
